version: '3.9'

services:
  jenkins:
    build:
      context: ../
      dockerfile: ./ci/jenkins/Dockerfile
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ..:/var/jenkins_home/workspace/sapient-fc
      - jenkins_home:/var/jenkins_home
    working_dir: /var/jenkins_home/workspace
    networks:
      - sapient-fc-ci-network

  sonarqube:
    build:
      context: ../
      dockerfile: ./ci/sonar/Dockerfile
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sapient-fc-ci-network

volumes:
  jenkins_home:

networks:
  sapient-fc-ci-network:
    driver: bridge
