version: '3.9'

services:
  jenkins:
    build:
      context: ../
      dockerfile: ./ci/jenkins/Dockerfile
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/folders/y4/mny5cbr11fgc8989snvcbbxc0000gp/T/podman/podman-machine-default-api.sock:/var/run/podman/podman.sock
    environment:
      - PODMAN_HOST=unix:///run/podman/podman.sock
    working_dir: /var/jenkins_home/workspace
    networks:
      - sapient-fc-ci-network

  sonarqube:
    build:
      context: ../
      dockerfile: ./ci/sonar/Dockerfile
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sapient-fc-ci-network
    depends_on:
      - db
    mem_limit: 4g

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    mem_limit: 1g

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:

networks:
  sapient-fc-ci-network:
    driver: bridge
